### ISSUE TITLE
How do I invoke this in a simulator?

### ISSUE THREAD

**Issue by dblock** [manekinekko/google-actions-twitter#1]
Total noob question I am sure, I just got a Google Home to play with.

```
> gactions simulate

Gactions needs access to your Google account. 
... all good here
User TTS (CTRL-C to stop): 
```

Now what do I type?

**Comment by dblock** [comment]
Oh I see, I need to `npm run preview` first, then I can do `talk to twitter`. Maybe add this to README along with keys requirements?

**Comment by manekinekko** [comment]
Hi @dblock the steps are described in the starter repo: https://github.com/manekinekko/google-actions-starter/blob/master/README.md#step-by-step

**Comment by dblock** [comment]
Thanks. That's to make something new @manekinekko. For these examples maybe something like "how to run this sample" would be useful. It's a lot of information for someone who never worked with a Google home thing :)
